### ISSUE TITLE
[FEATURE] Make it possible to chose a name for the test topic

### ISSUE THREAD

**Issue by ErlendFax** [Celerway/metamorphosis#11]
**Is your feature request related to a problem? Please describe.**
We have several topics, and the name `test` stands out in this list of topic names. One might think is less important, but since Metamorphosis uses it to test the connection it's actually kinda important. 

We also try to follow a topic name convention and the name `test` does not fit with this.

**Describe the solution you'd like**
Make it possible to set your own test topic name in a ENV, if its not set use `test`.

**Comment by perbu** [comment]
Thanks Erlend. This is useful.
It'll default to "test" but can be overridden with env TEST_MESSAGE_TOPIC.
Added in v0.2.6.
