### ISSUE TITLE
Make logs not go to stderr by default

### ISSUE THREAD

**Issue by ErlendFax** [Celerway/metamorphosis#8]
All logs from Metamorphosis is displayed as `error` in Google Logging - even if the log level is `debug` or `info` ... pretty annoying! 

![image](https://user-images.githubusercontent.com/21358646/187661519-c5876175-f5ca-48b3-96b3-3ab01977e649.png)

From [this discussion](https://github.com/sirupsen/logrus/issues/403), it seems the reason is that logrus sends *all* logs to stderr. Someone suggests a solution/workaround in the thread, but swapping to another log lib isn't much work either I would guess.

**Comment by perbu** [comment]
Hi Erlend.

I'm thinking I'm gonna see if I can drop logrus as a dependency and just log using the stdlib. Doing log levels is a bit more setup then, but it is manageable.

For when I get around to it, this seems sane: https://www.ardanlabs.com/blog/2013/11/using-log-package-in-go.html

**Comment by ErlendFax** [comment]
Cool!

I'm not a Golang developer so can't suggest much, unfortunately.

**Comment by ErlendFax** [comment]
Are contributions welcome? I'm considering trying it myself.

**Comment by perbu** [comment]
Yes, ofc. I'll get to around to it someday myself, but if you wanna lend a hand that would be great. My idea was something like this:
1) make a local package "log" / remove the dependency on logrus.
2) Implement log.Fatal, log.Error, log.Warn, log.Debug and log.Trace there
3) Have the log.Warn and log.Error go to stderr
4) Have the log.Info go to stdout
5) Hide all log.Debug behind a constant, build flag or parameter

Sounds doable, I think.

**Comment by edoger** [comment]
logrus is not very interested in fixing this problem at the moment. The PR submitted has been in an unmerged state. In the current state, if you must keep the use style of logrus, you can replace it with the log library [zkits-logger](https://github.com/edoger/zkits-logger) I built for this purpose.

**Comment by perbu** [comment]
@ErlendFax Could you have a look at #18 and tell me what you think?
